// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPTq9k1lrMq5szG9EJdfRIzcGZ6EbGpGE',
    appId: '1:786184839311:web:b1d6f4d227ba19b70190fa',
    messagingSenderId: '786184839311',
    projectId: 'komur-toptan-takip',
    authDomain: 'komur-toptan-takip.firebaseapp.com',
    storageBucket: 'komur-toptan-takip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOJCWwNm8hi0rjaiokHsBmbAUp9sPJOI',
    appId: '1:786184839311:android:79513e8e1b1d90430190fa',
    messagingSenderId: '786184839311',
    projectId: 'komur-toptan-takip',
    storageBucket: 'komur-toptan-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAm3oRB8-F2gf1urfL0JJ9t84L_EtdfS8',
    appId: '1:786184839311:ios:a596bd153df0dfed0190fa',
    messagingSenderId: '786184839311',
    projectId: 'komur-toptan-takip',
    storageBucket: 'komur-toptan-takip.firebasestorage.app',
    iosBundleId: 'com.example.p243301089AligorkemaydinFlutterProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAm3oRB8-F2gf1urfL0JJ9t84L_EtdfS8',
    appId: '1:786184839311:ios:a596bd153df0dfed0190fa',
    messagingSenderId: '786184839311',
    projectId: 'komur-toptan-takip',
    storageBucket: 'komur-toptan-takip.firebasestorage.app',
    iosBundleId: 'com.example.p243301089AligorkemaydinFlutterProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPTq9k1lrMq5szG9EJdfRIzcGZ6EbGpGE',
    appId: '1:786184839311:web:1d1505d92b71e8870190fa',
    messagingSenderId: '786184839311',
    projectId: 'komur-toptan-takip',
    authDomain: 'komur-toptan-takip.firebaseapp.com',
    storageBucket: 'komur-toptan-takip.firebasestorage.app',
  );
}
